### ISSUE TITLE
中文问题

### ISSUE THREAD

**Issue by xuzhendan** [vy/log4j2-redis-appender#6] opened 2019-07-25 01:51 UTC
写入中文redis不直接读取中文，可以处理下吗

**Comment by vy** [comment] 2019-07-25 07:37
Hey @xuzhendan! I've consulted to a Chinese friend and Google Translate, but neither managed to make sense of your question. Would you mind elaborating it (**in English!**) a bit, please? Some details on how to reproduce the problem locally will be really helpful.

**Comment by xuzhendan** [comment] 2019-07-29 02:59
![image](https://user-images.githubusercontent.com/6902752/62018635-1ab65300-b1ee-11e9-81fe-bd449ad54715.png)
I wan to show Chinese, in redis console.

**Comment by vy** [comment] 2019-08-01 11:55
@xuzhendan, a Log4j `Appender` has no control over the serialization of the `LogEvent`. You pass it a `Layout` (e.g., `PatternLayout`) and the `Appender` uses `byte[] Layout#toByteArray(LogEvent)` method to serialize the `LogEvent`. (See [RedisAppender.java#L138](https://github.com/vy/log4j2-redis-appender/blob/master/appender/src/main/java/com/vlkan/log4j2/redis/appender/RedisAppender.java#L138).)

Long story short, I suspect if your `Layout` is configured right. It looks like you are using the [`PatternLayout`](https://logging.apache.org/log4j/2.0/manual/layouts.html#PatternLayout). If so, did you configure its `charset` property right? If not, which appender are you using?

**Comment by vy** [comment] 2019-10-08 08:24
Closing the ticket due to insufficient information and reproduction path.

**Closed by vy** 2019-10-08 08:24 UTC
